### ISSUE TITLE
when use MarkovClickstream function, show invalid literal for int() with base 10: error

### ISSUE THREAD

**Issue by yangminglintw** [ismailuddin/markovclick#1]
Hi,

I used my own data to generate the input list to MarkovClickstream function, but it always show invalid literal for int() with base 10 error. Would you help me the correct format? 
Thank you.

update
I tired to convert my own label to P0,P1... and it worked. So, the input label only accept P0,P1...and it can not use other format?

**Comment by ismailuddin** [comment]
Could you provide some more details of your dataset and what code you've run so far? Maybe share a small portion of your data?

**Comment by yangminglintw** [comment]
I convert my data into the format like [['U'], ['U', 'P', 'O', 'U'], ['U']]. The string in the list I also tried the Chinese character and it did not work either.

**Comment by ismailuddin** [comment]
I've updated the package to better handle such cases. I was assuming your pages were of the format `PX` where X is a number, but I've removed that assumption. Please try it and it should work now!

**Comment by yangminglintw** [comment]
It work very well.
Thank you for support!!!
Nice tool to use.
